# POST https://yadonor-app.firebaseio.com/events/1.json

# {
#     "day": "02.01.2020",
#     "event": "Донорство крови"
# }

# DELETE https://yadonor-app.firebaseio.com/events/1.json

# PATCH  https://yadonor-app.firebaseio.com/events/1/-MDz4wxsl7ecuIM2ULB0.json

# {
#     "event": "Донорство плазмы"
# }

GET https://yadonor-app.firebaseio.com/events/1.json